"use client";
import {useMemo,useState} from "react";
import {Search,UserRound,UserPlus,MessageCircle} from "lucide-react";
type Contact={id:string;name:string;phone?:string;tags?:string[]};
export function ContactsPanel({contacts,onCreate,onOpen,canCreate}:{contacts:Contact[];onCreate:()=>void;onOpen:(contact:Contact)=>void;canCreate:boolean}){
 const [search,setSearch]=useState(""),[tag,setTag]=useState("");
 const tags=useMemo(()=>[...new Set(contacts.flatMap(c=>c.tags||[]))].sort(),[contacts]);
 const shown=contacts.filter(c=>(!tag||c.tags?.includes(tag))&&`${c.name} ${c.phone||""}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <section className="contacts-panel" aria-label="Contatos"><header><div><h1>Contatos</h1><p>{contacts.length} contatos na central</p></div><button className="solid-button" onClick={onCreate} disabled={!canCreate}><UserPlus size={18}/>Criar contato</button></header><div className="contacts-layout"><aside><h2>Etiquetas</h2><button className={!tag?"active":""} onClick={()=>setTag("")}>Todos os contatos</button>{tags.map(t=><button key={t} className={tag===t?"active":""} onClick={()=>setTag(t)}>{t}</button>)}{!tags.length&&<p>Nenhuma etiqueta cadastrada.</p>}</aside><div className="contacts-main"><label className="contacts-search"><Search size={18}/><input aria-label="Buscar contatos" placeholder="Buscar nome ou WhatsApp" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="contacts-table-wrap"><table><thead><tr><th>Contato</th><th>WhatsApp</th><th>Etiquetas</th><th>Conversa</th></tr></thead><tbody>{shown.map(c=><tr key={c.id}><td><span className="contact-cell"><span className="contact-avatar"><UserRound size={20}/></span><strong>{c.name}</strong></span></td><td>{c.phone?`+${c.phone.replace(/\D/g,"")}`:"Não informado"}</td><td>{c.tags?.map(t=><span className="contact-tag" key={t}>{t}</span>)}</td><td><button className="contact-open" aria-label={`Abrir conversa com ${c.name}`} onClick={()=>onOpen(c)}><MessageCircle size={17}/>Abrir</button></td></tr>)}</tbody></table>{!shown.length&&<p className="contacts-empty">Nenhum contato encontrado.</p>}</div></div></div></section>;
}
